/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataInput_pkg;

import Instrument_pkg.Instrument;
import JDBCqueries_pkg.JDBCqueries;
import java.util.ArrayList;

/**
 *
 * @author David Kloosterman
 */
public class DataInputForm extends javax.swing.JFrame {

    /**
     * Creates new form DataInputForm
     */
    public DataInputForm() {
        initComponents();

        ObjectSelectComboBox.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRUD_ButtonGroup = new javax.swing.ButtonGroup();
        UpperLeftPanel = new javax.swing.JPanel();
        ObjectSelectComboBox = new javax.swing.JComboBox<>();
        CreateRadioButton = new javax.swing.JRadioButton();
        ReadRadioButton = new javax.swing.JRadioButton();
        UpdateRadioButton = new javax.swing.JRadioButton();
        DeleteRadioButton = new javax.swing.JRadioButton();
        UpperRightPanel = new javax.swing.JPanel();
        LowerLeftPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        submitQueryButton = new javax.swing.JButton();
        LowerRightPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Input");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        UpperLeftPanel.setBackground(new java.awt.Color(204, 204, 255));
        UpperLeftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ObjectSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Instrument", "Instrument Deployment", "Cartridge", "Test Instances", "Errors" }));
        ObjectSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjectSelectComboBoxActionPerformed(evt);
            }
        });

        CRUD_ButtonGroup.add(CreateRadioButton);
        CreateRadioButton.setText("Create");

        CRUD_ButtonGroup.add(ReadRadioButton);
        ReadRadioButton.setSelected(true);
        ReadRadioButton.setText("Read");

        CRUD_ButtonGroup.add(UpdateRadioButton);
        UpdateRadioButton.setText("Update");

        CRUD_ButtonGroup.add(DeleteRadioButton);
        DeleteRadioButton.setText("Delete");

        javax.swing.GroupLayout UpperLeftPanelLayout = new javax.swing.GroupLayout(UpperLeftPanel);
        UpperLeftPanel.setLayout(UpperLeftPanelLayout);
        UpperLeftPanelLayout.setHorizontalGroup(
            UpperLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLeftPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(UpperLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteRadioButton)
                    .addComponent(UpdateRadioButton)
                    .addComponent(CreateRadioButton)
                    .addComponent(ReadRadioButton)
                    .addComponent(ObjectSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        UpperLeftPanelLayout.setVerticalGroup(
            UpperLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObjectSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteRadioButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(UpperLeftPanel);

        UpperRightPanel.setBackground(new java.awt.Color(204, 204, 255));
        UpperRightPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout UpperRightPanelLayout = new javax.swing.GroupLayout(UpperRightPanel);
        UpperRightPanel.setLayout(UpperRightPanelLayout);
        UpperRightPanelLayout.setHorizontalGroup(
            UpperRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        UpperRightPanelLayout.setVerticalGroup(
            UpperRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        getContentPane().add(UpperRightPanel);

        LowerLeftPanel.setBackground(new java.awt.Color(204, 204, 255));
        LowerLeftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inputTextArea.setColumns(20);
        inputTextArea.setLineWrap(true);
        inputTextArea.setRows(5);
        inputTextArea.setText("Query");
        jScrollPane2.setViewportView(inputTextArea);

        submitQueryButton.setText("Submit");

        javax.swing.GroupLayout LowerLeftPanelLayout = new javax.swing.GroupLayout(LowerLeftPanel);
        LowerLeftPanel.setLayout(LowerLeftPanelLayout);
        LowerLeftPanelLayout.setHorizontalGroup(
            LowerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LowerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(LowerLeftPanelLayout.createSequentialGroup()
                        .addComponent(submitQueryButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LowerLeftPanelLayout.setVerticalGroup(
            LowerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitQueryButton)
                .addContainerGap())
        );

        getContentPane().add(LowerLeftPanel);

        LowerRightPanel.setBackground(new java.awt.Color(204, 204, 255));
        LowerRightPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        resultTextArea.setText("SQL Result");
        jScrollPane1.setViewportView(resultTextArea);

        javax.swing.GroupLayout LowerRightPanelLayout = new javax.swing.GroupLayout(LowerRightPanel);
        LowerRightPanel.setLayout(LowerRightPanelLayout);
        LowerRightPanelLayout.setHorizontalGroup(
            LowerRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        LowerRightPanelLayout.setVerticalGroup(
            LowerRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(LowerRightPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ObjectSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjectSelectComboBoxActionPerformed
        try {
            ArrayList<String> columnNames = new ArrayList<String>();
            JDBCqueries queries = new JDBCqueries();
            String tableName = null;

            resultTextArea.setText((String) ObjectSelectComboBox.getSelectedItem());
            switch ((String) ObjectSelectComboBox.getSelectedItem()) {

                case "Instrument":
                    tableName = "Instrument_Manufactured";
                    break;

                case "Instrument Deployment":
                    tableName = "Instrument_Deployed";
                    break;

                case "Cartridge":
                    tableName = "Cartridge_Manufactured";
                    break;
                    
                case "Test Instances":
                    tableName = "Clinical_Test_Instance";
                    break;
                    
                case "Errors":
                    tableName = "Errors";
                    break;
                    
                default:
                    System.out.println("Unknown button pressed");
                    break;
            }

            resultTextArea.setText("");
            columnNames = queries.getTableColumnNames(tableName);
            for (String Name : columnNames) {
                resultTextArea.setText(resultTextArea.getText() + Name + "\n");
            }

        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally 
    }//GEN-LAST:event_ObjectSelectComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataInputForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CRUD_ButtonGroup;
    private javax.swing.JRadioButton CreateRadioButton;
    private javax.swing.JRadioButton DeleteRadioButton;
    private javax.swing.JPanel LowerLeftPanel;
    private javax.swing.JPanel LowerRightPanel;
    private javax.swing.JComboBox<String> ObjectSelectComboBox;
    private javax.swing.JRadioButton ReadRadioButton;
    private javax.swing.JRadioButton UpdateRadioButton;
    private javax.swing.JPanel UpperLeftPanel;
    private javax.swing.JPanel UpperRightPanel;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton submitQueryButton;
    // End of variables declaration//GEN-END:variables
}
